name: zip builder
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r test_zip_stuff.zip . -x ".git/*" ".github/*"
    - name: Claim done
      run: echo "done"
